name: Build & Test

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Install Bun
        run: npm install -g bun
      - run: bun install
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: bun generate
      - run: bun run test --coverage
      - name: Run Biome
        run: biome ci .
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}